import {firebaseConfig,vapidKey} from "./firebase-config.js";
const configured=firebaseConfig.apiKey&&!firebaseConfig.apiKey.includes("HIER_");
let fb=null,db=null,auth=null;
if(configured){try{const [a,u,f]=await Promise.all([import("https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js"),import("https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js"),import("https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js")]);const app=a.initializeApp(firebaseConfig);auth=u.getAuth(app);await u.signInAnonymously(auth);db=f.getFirestore(app);fb={f};}catch(e){console.warn(e)}}
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];const today=()=>new Date().toISOString().slice(0,10);const add=n=>{let d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};const id=p=>p+"-"+crypto.randomUUID();const fmt=x=>x?new Intl.DateTimeFormat("de-DE",{weekday:"short",day:"2-digit",month:"2-digit"}).format(new Date(x+"T12:00:00")):"";const esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const demo={tasks:[{id:"t1",title:"Müll rausstellen",due:today(),priority:"Normal",done:false,recurrence:"Wöchentlich"},{id:"t2",title:"Rechnung bezahlen",due:today(),priority:"Dringend",done:false,recurrence:"Nein"}],shopping:[{id:"s1",title:"Milch",done:false},{id:"s2",title:"Bananen",done:false},{id:"s3",title:"Windeln",done:false}],events:[{id:"e1",title:"Kinderarzt",date:add(1),time:"16:30",person:"Malia",category:"Arzt",location:""},{id:"e2",title:"Familienzeit",date:add(3),time:"11:00",person:"Familie",category:"Freizeit",location:""}],pinboard:[{id:"p1",text:"Paket kommt heute."}],expenses:[],recipes:[{title:"Spaghetti Bolognese"},{title:"Hähnchen mit Reis"},{title:"Wraps"}],products:[{id:"p1",name:"Milch",shop:"REWE"},{id:"p2",name:"Windeln",shop:"dm"},{id:"p3",name:"Wasser",shop:"REWE"},{id:"p4",name:"Feuchttücher",shop:"dm"}]};
const state={user:null,data:structuredClone(demo)};const keys=["tasks","shopping","events","pinboard","expenses","recipes","products"];
function load(){if(!db){try{state.data={...state.data,...JSON.parse(localStorage.getItem("kuhlfamily-v1")||"{}")}}catch{}}}function store(){if(!db)localStorage.setItem("kuhlfamily-v1",JSON.stringify(state.data))}
async function save(key,item){if(db){await fb.f.setDoc(fb.f.doc(db,key,item.id),item,{merge:true})}else{let i=state.data[key].findIndex(x=>x.id===item.id);i>=0?state.data[key][i]={...state.data[key][i],...item}:state.data[key].unshift(item);store();render()}}
async function watch(){if(db){for(const key of keys){fb.f.onSnapshot(fb.f.collection(db,key),s=>{state.data[key]=s.docs.map(d=>({id:d.id,...d.data()}));render()})}}else render()}
function item(icon,title,sub=""){return `<div class="item"><span>${icon}</span><div><b>${esc(title)}</b>${sub?`<small>${esc(sub)}</small>`:""}</div></div>`}function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
$$('[data-user]').forEach(b=>b.onclick=()=>{state.user=b.dataset.user;$("#gate").classList.add("hidden");$("#app").classList.remove("hidden");$("#hello").textContent="Hallo "+state.user;$("#date").textContent=new Intl.DateTimeFormat("de-DE",{weekday:"long",day:"2-digit",month:"long"}).format(new Date());render()});$("#changeUser").onclick=()=>{$("#app").classList.add("hidden");$("#gate").classList.remove("hidden")};
$$('[data-nav]').forEach(b=>b.onclick=()=>{$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.nav).classList.add('active');$$('[data-nav]').forEach(x=>x.classList.toggle('active',x===b));scrollTo(0,0)});
function render(){let openT=state.data.tasks.filter(x=>!x.done),openS=state.data.shopping.filter(x=>!x.done),up=[...state.data.events].filter(x=>x.date>=today()).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));$('#taskPreview').innerHTML=openT.slice(0,3).map(x=>item('✅',x.title,fmt(x.due)+' · '+x.priority)).join('')||item('✓','Alles erledigt');$('#shopPreview').innerHTML=openS.slice(0,4).map(x=>item('🛒',x.title)).join('')||item('🛒','Liste ist leer');$('#eventPreview').innerHTML=up.slice(0,3).map(x=>item('📅',x.title,fmt(x.date)+' '+(x.time||'')+' · '+x.person)).join('')||item('📅','Keine Termine');$('#pinPreview').innerHTML=state.data.pinboard.slice(0,3).map(x=>item('📌',x.text)).join('')||item('📌','Keine Hinweise');let imp=[...openT.filter(x=>x.priority==='Dringend'||x.due<today()).map(x=>({t:x.title,s:x.due<today()?'Überfällig':'Dringend'})),...up.filter(x=>x.date<=add(1)).map(x=>({t:x.title,s:fmt(x.date)+' '+(x.time||'')}))];$('#important').innerHTML=imp.slice(0,4).map(x=>item('⚠️',x.t,x.s)).join('')||item('✓','Nichts Dringendes');
$('#taskList').innerHTML=state.data.tasks.map(x=>`<div class="row"><button class="check ${x.done?'done':''}" data-task="${x.id}">${x.done?'✓':''}</button><div class="grow"><b>${esc(x.title)}</b><small>${fmt(x.due)} · ${esc(x.priority)}${x.doneBy?' · Erledigt von '+esc(x.doneBy):''}</small></div><span class="badge">${esc(x.recurrence||'Nein')}</span></div>`).join('');$$('[data-task]').forEach(b=>b.onclick=()=>{let x=state.data.tasks.find(t=>t.id===b.dataset.task);save('tasks',{...x,done:!x.done,doneBy:!x.done?state.user:null})});
$('#shopList').innerHTML=state.data.shopping.map(x=>`<div class="row"><button class="check ${x.done?'done':''}" data-shop="${x.id}">${x.done?'✓':''}</button><div class="grow"><b>${esc(x.title)}</b>${x.doneBy?`<small>Erledigt von ${esc(x.doneBy)}</small>`:''}</div></div>`).join('');$$('[data-shop]').forEach(b=>b.onclick=()=>{let x=state.data.shopping.find(t=>t.id===b.dataset.shop);save('shopping',{...x,done:!x.done,doneBy:!x.done?state.user:null})});
$('#products').innerHTML=state.data.products.map(x=>`<button class="product" data-product="${x.id}"><span>${x.shop==='dm'?'🧴':'🛍️'}</span><b>${esc(x.name)}</b><small>${esc(x.shop)}</small></button>`).join('');$$('[data-product]').forEach(b=>b.onclick=()=>{let p=state.data.products.find(x=>x.id===b.dataset.product);save('shopping',{id:id('s'),title:p.name,done:false,addedBy:state.user});toast(p.name+' hinzugefügt')});
$('#eventList').innerHTML=[...state.data.events].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(x=>`<div class="row person-${x.person}"><div class="grow"><b>${esc(x.title)}</b><small>${fmt(x.date)} ${esc(x.time)} · ${esc(x.person)} · ${esc(x.category)}</small></div>${x.location?`<a target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.location)}">Maps</a>`:''}</div>`).join('')}
$('#shopForm').onsubmit=e=>{e.preventDefault();let v=$('#shopInput').value.trim();if(v){save('shopping',{id:id('s'),title:v,done:false,addedBy:state.user});$('#shopInput').value=''}};$('#meal').onclick=()=>{let a=state.data.recipes;$('#mealResult').textContent=a.length?' '+a[Math.floor(Math.random()*a.length)].title:' Noch keine Rezepte'};
$('#fab').onclick=()=>$('#quick').showModal();$$('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function f(label,name,type='text'){return `<label>${label}<input name="${name}" type="${type}"></label>`}function sel(label,name,a){return `<label>${label}<select name="${name}">${a.map(x=>`<option>${x}</option>`).join('')}</select></label>`}
$$('[data-add]').forEach(b=>b.onclick=()=>{let t=b.dataset.add;$('#quick').close();let h={task:'Aufgabe hinzufügen',event:'Termin hinzufügen',shopping:'Einkauf hinzufügen',expense:'Ausgabe erfassen',pin:'Pinnwand-Notiz'}[t];$('#editorTitle').textContent=h;let x='';if(t==='task')x=f('Aufgabe','title')+f('Fällig am','due','date')+sel('Priorität','priority',['Normal','Wichtig','Dringend'])+sel('Wiederholung','recurrence',['Nein','Täglich','Wöchentlich','Alle 2 Wochen','Monatlich']);if(t==='event')x=f('Termin','title')+f('Datum','date','date')+f('Uhrzeit','time','time')+sel('Für wen?','person',['Dominic','Sabrina','Malia','Familie'])+sel('Kategorie','category',['Familie','Malia','Geburtstag','Arzt','Kita','Freizeit','Sonstiges'])+f('Ort','location');if(t==='shopping')x=f('Artikel','title');if(t==='expense')x=f('Betrag','amount','number')+sel('Kategorie','category',['Lebensmittel','Drogerie','Freizeit','Auto','Kind','Wohnen','Sonstiges'])+f('Verwendungszweck optional','note');if(t==='pin')x='<label>Notiz<textarea name="text"></textarea></label>';$('#editorForm').innerHTML=x+`<input type="hidden" name="kind" value="${t}"><button class="primary wide">Speichern</button>`;$('#editor').showModal()});
$('#editorForm').onsubmit=e=>{e.preventDefault();let d=new FormData(e.target),t=d.get('kind');if(t==='task')save('tasks',{id:id('t'),title:d.get('title'),due:d.get('due'),priority:d.get('priority'),recurrence:d.get('recurrence'),done:false});if(t==='event')save('events',{id:id('e'),title:d.get('title'),date:d.get('date'),time:d.get('time'),person:d.get('person'),category:d.get('category'),location:d.get('location')});if(t==='shopping')save('shopping',{id:id('s'),title:d.get('title'),done:false});if(t==='expense')save('expenses',{id:id('x'),amount:Number(d.get('amount')),category:d.get('category'),note:d.get('note'),date:today()});if(t==='pin')save('pinboard',{id:id('p'),text:d.get('text')});$('#editor').close();toast('Gespeichert')};
load();watch();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});